-- Full schema for E2EE Team Pins
-- Run this in your Supabase SQL Editor

-- Encrypted pins
create table if not exists encrypted_pins (
  id bigint generated by default as identity primary key,
  team_id text not null,
  pin_id uuid not null unique,
  ciphertext text not null,
  nonce text not null,
  is_public boolean default false,
  created_at timestamptz default now()
);
alter table encrypted_pins enable row level security;
drop policy if exists "open access" on encrypted_pins;
drop policy if exists "pins_select" on encrypted_pins;
drop policy if exists "pins_insert" on encrypted_pins;
drop policy if exists "pins_update" on encrypted_pins;
drop policy if exists "pins_delete" on encrypted_pins;
create policy "pins_select" on encrypted_pins for select
  using (is_public = true or auth.role() = 'authenticated');
create policy "pins_insert" on encrypted_pins for insert
  with check (auth.role() = 'authenticated');
create policy "pins_update" on encrypted_pins for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
create policy "pins_delete" on encrypted_pins for delete
  using (auth.role() = 'authenticated');

-- Encrypted drawings
create table if not exists encrypted_drawings (
  id bigint generated by default as identity primary key,
  team_id text not null,
  drawing_id uuid not null unique,
  encrypted_geojson text not null,
  nonce text not null,
  is_public boolean default false,
  created_at timestamptz default now()
);
alter table encrypted_drawings enable row level security;
drop policy if exists "drawings_select" on encrypted_drawings;
drop policy if exists "drawings_insert" on encrypted_drawings;
drop policy if exists "drawings_update" on encrypted_drawings;
drop policy if exists "drawings_delete" on encrypted_drawings;
create policy "drawings_select" on encrypted_drawings for select
  using (is_public = true or auth.role() = 'authenticated');
create policy "drawings_insert" on encrypted_drawings for insert
  with check (auth.role() = 'authenticated');
create policy "drawings_update" on encrypted_drawings for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
create policy "drawings_delete" on encrypted_drawings for delete
  using (auth.role() = 'authenticated');

-- Team membership
create table if not exists team_members (
  team_id text not null,
  user_id text not null,
  email text,
  display_name text,
  role text default 'member',
  primary key (team_id, user_id)
);
alter table team_members enable row level security;
drop policy if exists "members_select" on team_members;
drop policy if exists "members_insert" on team_members;
drop policy if exists "members_update" on team_members;
drop policy if exists "members_delete" on team_members;
create policy "members_select" on team_members for select using (true);
create policy "members_insert" on team_members for insert with check (auth.uid() = user_id);
create policy "members_update" on team_members for update using (auth.role() = 'authenticated');
create policy "members_delete" on team_members for delete using (auth.role() = 'authenticated');

-- Team keypair (publicly readable for guests, only authenticated can write)
create table if not exists team_secrets (
  team_id text primary key,
  public_key text not null,
  secret_key text not null
);
alter table team_secrets enable row level security;
drop policy if exists "secrets_select" on team_secrets;
drop policy if exists "secrets_insert" on team_secrets;
create policy "secrets_select" on team_secrets for select using (true);
create policy "secrets_insert" on team_secrets for insert with check (auth.role() = 'authenticated');

-- Team DEK (publicly readable for guests, only authenticated can write)
create table if not exists team_dek (
  team_id text primary key,
  wrapped_dek text not null
);
alter table team_dek enable row level security;
drop policy if exists "dek_select" on team_dek;
drop policy if exists "dek_insert" on team_dek;
drop policy if exists "dek_update" on team_dek;
create policy "dek_select" on team_dek for select using (true);
create policy "dek_insert" on team_dek for insert with check (auth.role() = 'authenticated');
create policy "dek_update" on team_dek for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Invite tokens
create table if not exists team_invites (
  token text primary key,
  team_id text not null,
  created_by text not null,
  created_at timestamptz default now(),
  used boolean default false
);
alter table team_invites enable row level security;
drop policy if exists "invites_select" on team_invites;
drop policy if exists "invites_insert" on team_invites;
drop policy if exists "invites_delete" on team_invites;
drop policy if exists "invites_update" on team_invites;
create policy "invites_select" on team_invites for select using (true);
create policy "invites_insert" on team_invites for insert with check (auth.role() = 'authenticated');
create policy "invites_delete" on team_invites for delete using (auth.role() = 'authenticated');
create policy "invites_update" on team_invites for update using (true) with check (true);

-- Team settings
create table if not exists team_settings (
  team_id text primary key,
  require_token boolean default false
);
alter table team_settings enable row level security;
drop policy if exists "settings_all" on team_settings;
create policy "settings_all" on team_settings for all using (true) with check (true);
