/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const compress_gzip: (a: number, b: number) => [number, number];
export const compress_gzip_max: (a: number, b: number) => [number, number];
export const compute_geometry: (a: number, b: number) => [number, number];
export const decode_hex: (a: number, b: number) => [number, number];
export const decompress_gzip: (a: number, b: number) => [number, number, number, number];
export const decrypt_annotation: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const decrypt_bytes_with_password: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const decrypt_geojson: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const decrypt_pin_data: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const decrypt_raw_bytes: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const decrypt_with_password: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const deserialize_container: (a: number, b: number) => [number, number, number, number];
export const detect_freehand_shape: (a: number, b: number) => [number, number];
export const encode_hex: (a: number, b: number) => [number, number];
export const encrypt_annotation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: bigint, i: number, j: number) => [number, number, number];
export const encrypt_bytes_with_password: (a: number, b: number, c: number, d: number) => [number, number, number];
export const encrypt_geojson: (a: number, b: number, c: number, d: number) => [number, number, number];
export const encrypt_pin_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const encrypt_raw_bytes: (a: number, b: number, c: number, d: number) => [number, number, number];
export const encrypt_with_password: (a: number, b: number, c: number, d: number) => [number, number, number];
export const generate_dek: () => [number, number];
export const generate_qr_svg: (a: number, b: number) => [number, number];
export const generate_signing_keypair: () => any;
export const generate_user_keypair: () => any;
export const generate_user_keypair_from_password: (a: number, b: number, c: number, d: number) => any;
export const generate_uuid: () => [number, number];
export const hw_model_name: (a: number) => [number, number];
export const mesh_chunk_encode: (a: number, b: number) => [number, number];
export const serialize_container: (a: number, b: number) => [number, number, number, number];
export const sign: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const simplify_freehand: (a: number, b: number, c: number) => [number, number];
export const unwrap_dek: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const verify: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const wrap_dek: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const reticulum_address: (a: number, b: number) => [number, number];
export const reticulum_generate_identity: () => [number, number];
export const reticulum_hash_data: (a: number, b: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
