[package]
name = "e2e-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
chacha20poly1305 = "0.10"
rand = "0.8"
x25519-dalek = { version = "2", features = ["static_secrets"] }
hkdf = "0.12"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
uuid = { version = "1", features = ["v4", "js"] }
qrcode = "0.14"
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
ed25519-dalek = "2"
reticulum-rs-core = "0.2.0"
base64 = "0.22"
indexmap = "2"
js-sys = "0.3"
